### ISSUE TITLE
Can't get a connection working

### ISSUE THREAD

**Issue by jackm96** [clayface/VF-UK-Asterisk-config#1]
Hi, Not sure if you can help but worth a try, trying to load this config on my system but I can't seem to get SIP to register. 

Keep seeing this error:

[Jan  7 20:20:39] DEBUG[562]: res_pjsip_outbound_registration.c:1239 handle_registration_response: Processing REGISTER response 408 from server 'sip:resvoip.vodafone.co.uk' for client 'sip:voi000xxxxxx@resvoip.vodafone.co.uk

I have ran a packet capture and I can see request going out to Vodafone but nothing coming back. Does yours still work?

**Comment by clayface** [comment]
You might need to add another line under [acl]:
permit = 148.252.154.0/24

Failing that it's possible your router is modifying the DSCP value or
source port. These mustn't be changed or you won't get any responses.
If possible, run the packet capture on the router rather than the asterisk
host and compare these values.

**Comment by jackm96** [comment]
Thanks for the reply, I got it registered and then it stopped working...
seems to be going in circles, I am running the packet capture on PFsense,
when it was working i could see traffic talking between me and VF, but now
its stopped its getting no reply from VF.

How are you running this? ive tried asterisk and freepbx, got it working on
both and not working on both so feel like im missing something obvious..

cheers

**Comment by jackm96** [comment]
Got it 90% working now, can make/receive calls, but get no inbound audio on the trunk on either outbound or inbound calls. outbound audio is fine, ran a packet trace and im getting no RTP packets from VF.... must be one setting im missing... ive set the RTP setting in asterisk and allowed that on the router...

**Comment by jackm96** [comment]
All sorted finally, as I have differnt VLANs setup here I needed to add multiple subnets in the ACL. I even managed to get this trunked into 3CX via asterisk. Thanks for supplying this config Its helped massively.
